SELECT	[INFORMATION_SCHEMA].[COLUMNS].[COLUMN_NAME]
		, [INFORMATION_SCHEMA].[COLUMNS].[DATA_TYPE]
		, [INFORMATION_SCHEMA].[COLUMNS].[IS_NULLABLE]
		, [INFORMATION_SCHEMA].[COLUMNS].[CHARACTER_MAXIMUM_LENGTH]
		, [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_PRECISION]
		, [INFORMATION_SCHEMA].[COLUMNS].[NUMERIC_SCALE]
		, [INFORMATION_SCHEMA].[COLUMNS].[COLUMN_DEFAULT]
		, [INFORMATION_SCHEMA].[COLUMNS].[COLLATION_NAME]
FROM	[INFORMATION_SCHEMA].[COLUMNS]
WHERE	[INFORMATION_SCHEMA].[COLUMNS].[TABLE_SCHEMA] 		= ?
		AND [INFORMATION_SCHEMA].[COLUMNS].[TABLE_NAME]		= ?
;